# [START gae_python37_cloudsql_config] 
runtime: python39
 
env_variables: 
  CLOUD_SQL_USERNAME: Admin  
  CLOUD_SQL_PASSWORD: Admin
  CLOUD_SQL_DATABASE_NAME: musiclist
  CLOUD_SQL_CONNECTION_NAME: adlab-10-2021:europe-west2:adproject 
# [END gae_python37_cloudsql_config] 